---
- hosts: all

  tasks:
   - name: install gnome x windows
     yum: state=latest name={{ item }} update_cache=yes
     with_items:
     - "@X Window System"
     - "gnome-classic-session"
     - "gnome-terminal"
     - "control-center"
     - "liberation-mono-fonts"
     
   - name: unlink
     shell: "unlink /etc/systemd/system/default.target & ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target"
   
   - name: Set hostname
     hostname: name="{{ ansible_ssh_host }}"
     notify:
      - Restart server
      - Wait for server to restart

  handlers:
   - name: Restart server
     command: reboot
     async: 0
     poll: 0
     ignore_errors: true
   
   - name: Wait for server to restart
     local_action:
      module: wait_for
       host= "{{ ansible_ssh_host }}"
       port=22
       delay=10
       timeout=300
