---
- hosts: all

  tasks:
  
  - name: install x windows
    yum: state=latest name="@X Window System" update_cache=yes
  
  - name: install gnome desktop
    yum: state=latest name={{ item }} update_cache=yes
    with_items:
     - "gnome-classic-session"
     - "gnome-terminal"
     - "control-center"
     - "liberation-mono-fonts"
     
  - name: unlink
    shell: "unlink /etc/systemd/system/default.target & ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target"
   
  - name: reboot
    shell: reboot
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 10
    connection: local

