---
- hosts: all

  tasks:
   - name: install gnome x windows
     yum: state=latest name={{ item }} update_cache=yes
     with_items:
     - "@X Window System"
     - "gnome-classic-session"
     - "gnome-terminal"
     - "control-center"
     - "liberation-mono-fonts"
     
   - name: unlink
     shell: "unlink /etc/systemd/system/default.target & ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target"
   
   - name:
     shell: "reboot"
     async: 0
     poll: 0
      
   - name: Wait for server to restart
     local_action:
      module: wait_for
       host='{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
       port=22
       delay=1
       timeout=300
